spring:
  application:
    name: service-registry

  config:
    import: "configserver:"

  cloud:
    config:
      uri: http://localhost:9000

  eureka:
    client:
      registerWithEureka: false # Stops the registry from registering itself
      fetchRegistry: false      # Stops it from trying to fetch a registry from another server

